#!/usr/bin/env ruby

require 'bundler'
Bundler.setup

lib = File.expand_path('../../lib', __FILE__)
$:.unshift(lib) if !$:.include?(lib)

require 'fileutils'
require 'mini_magick'
require 'ruby-progressbar'
require 'thyme/db'
require 'thyme/photo'
require 'thyme/set'

MiniMagick.configure do |config|
  config.validate_on_create = false
  config.validate_on_write = false
end

module Thyme
  class Photo
    def generate_thumbs
      generate_thumb(path, '1000x1000', :big) # use original file
      generate_thumb(thumb_path(:big), '200x200', :small) # use big thumb
    end

    private

    def generate_thumb(src_path, size, suffix)
      return if File.exist?(thumb_path(suffix))

      image = MiniMagick::Image.open(src_path, File.extname(src_path))

      image.combine_options do |c|
        c.auto_orient
        c.strip

        if suffix == :small
          c.resize("#{size}^")
          c.gravity('center')
          c.extent(size)
        elsif suffix == :big
          c.resize(size)
        end
      end

      image.write(thumb_path(suffix))
    end
  end
end

FileUtils.mkdir_p Thyme::Photo::THUMBS_PATH

progress_bar = ProgressBar.create(
  title:  'thumb gen.',
  total:  Thyme::Photo.count,
  format: '%a |%b>%i| %p%% %t'
)

Thyme::Photo.reverse_order(:taken_at).each do |photo|
  photo.generate_thumbs
  progress_bar.increment
end
